work on #4, still failing but different error so progress! specified optimization objective and received 404 error
2020-01-24 17:34:55> Request Status Code: 404
2020-01-24 17:34:55> API returned error: Dataset does not exist.
2020-01-24 17:34:55> No retry attempted: Dataset does not exist.
Error: API returned: Dataset does not exist.
```